# Wolfcore build config
DIST_CODENAME="bookworm"
MIRROR="http://deb.debian.org/debian"
ARCH="amd64"
HOSTNAME="wolfcore"
ROOT_PASSWORD="wolf"

ROOTFS_DIR="out/rootfs"
IMAGE_PATH="out/wolfcore.img"
IMAGE_SIZE_MB="4096"
LOOP_MOUNT_DIR="out/mnt"

# Kernel package (Debian)
KERNEL_PACKAGE="linux-image-amd64"
